name: Playwright CI with Allure

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --reporter=allure-playwright
        continue-on-error: true

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
      - name: Calculate Pass Percentage
        id: results
        run: |
          TOTAL=$(jq '.statistic.total' allure-report/widgets/summary.json)
          PASSED=$(jq '.statistic.passed' allure-report/widgets/summary.json)
          FAILED=$(jq '.statistic.failed' allure-report/widgets/summary.json)

          if [ "$TOTAL" -eq 0 ]; then
            PERCENT=0
          else
            PERCENT=$((PASSED * 100 / TOTAL))
          fi

          if [ "$TOTAL" -eq 0 ]; then
            PERCENTF=0
          else
            PERCENTF=$((FAILED * 100 / TOTAL))
          fi

          DATE=$(date +'%d-%m-%Y')

          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "percent=$PERCENT" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT
          echo "percentf=$PERCENTF" >> $GITHUB_OUTPUT

      - name: Send Playwright Report Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASS }}
          subject: "PC-Automation-${{ steps.results.outputs.date }}-[${{ steps.results.outputs.percent }}%]-Passed"
          body: |
            Hello Team Members, 

            Allure Report is ready.

            You have total ${{steps.results.outputs.total}} cases. Passed ${{ steps.results.outputs.percent }}% and Failed ${{ steps.results.outputs.percentf }}%.
            For more details:- https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

            Thanks & Regards 
            Vishnu M 
            
          to: vishnucleago123@gmail.com,nagashreegnckm@gmail.com
          from: ${{ secrets.GMAIL_USER }}